In [157]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

### Data Preparation

In [158]:
file = "/Users/ausin/Downloads/Food Waste data and research - by country.csv"
data = pd.read_csv(file)
data

,Country,combined figures (kg/capita/year),Household estimate (kg/capita/year),Household estimate (tonnes/year),Retail estimate (kg/capita/year),Retail estimate (tonnes/year),Food service estimate (kg/capita/year),Food service estimate (tonnes/year),Confidence in estimate,M49 code,Region,Source
0,Afghanistan,126,82,3109153,16,594982,28,1051783,Very Low Confidence,4,Southern Asia,https://www.unep.org/resources/report/unep-foo...
1,Albania,127,83,238492,16,45058,28,79651,Very Low Confidence,8,Southern Europe,https://www.unep.org/resources/report/unep-foo...
2,Algeria,135,91,3918529,16,673360,28,1190335,Very Low Confidence,12,Northern Africa,https://www.unep.org/resources/report/unep-foo...
3,Andorra,123,84,6497,13,988,26,1971,Low Confidence,20,Southern Europe,https://www.unep.org/resources/report/unep-foo...
4,Angola,144,100,3169523,16,497755,28,879908,Very Low Confidence,24,Sub-Saharan Africa,https://www.unep.org/resources/report/unep-foo...
...,...,...,...,...,...,...,...,...,...,...,...,...
209,Venezuela (Boliv. Rep. of),116,72,2065461,16,445994,28,788407,Very Low Confidence,862,Latin America and the Caribbean,https://www.unep.org/resources/report/unep-foo...
210,Viet Nam,120,76,7346717,16,1508689,28,2666991,Very Low Confidence,704,South-eastern Asia,https://www.unep.org/resources/report/unep-foo...
211,Yemen,148,104,3026946,16,456099,28,806270,Very Low Confidence,887,Western Asia,https://www.unep.org/resources/report/unep-foo...
212,Zambia,122,78,1391729,16,279350,28,493822,Very Low Confidence,894,Sub-Saharan Africa,https://www.unep.org/resources/report/unep-foo...
213,Zimbabwe,144,100,1458564,16,229059,28,404920,Very Low Confidence,716,Sub-Saharan Africa,https://www.unep.org/resources/report/unep-foo...

In [159]:
import pandas as pd

df = pd.DataFrame({
    "roll-no": [1,2,3],
    "homework": ['submitted','not-submitted',np.nan]
})
df.notnull()

   roll-no  homework
0     True      True
1     True      True
2     True     False

In [160]:
data.head(20)

,Country,combined figures (kg/capita/year),Household estimate (kg/capita/year),Household estimate (tonnes/year),Retail estimate (kg/capita/year),Retail estimate (tonnes/year),Food service estimate (kg/capita/year),Food service estimate (tonnes/year),Confidence in estimate,M49 code,Region,Source
0,Afghanistan,126,82,3109153,16,594982,28,1051783,Very Low Confidence,4,Southern Asia,https://www.unep.org/resources/report/unep-foo...
1,Albania,127,83,238492,16,45058,28,79651,Very Low Confidence,8,Southern Europe,https://www.unep.org/resources/report/unep-foo...
2,Algeria,135,91,3918529,16,673360,28,1190335,Very Low Confidence,12,Northern Africa,https://www.unep.org/resources/report/unep-foo...
3,Andorra,123,84,6497,13,988,26,1971,Low Confidence,20,Southern Europe,https://www.unep.org/resources/report/unep-foo...
4,Angola,144,100,3169523,16,497755,28,879908,Very Low Confidence,24,Sub-Saharan Africa,https://www.unep.org/resources/report/unep-foo...
5,Antigua and Barbuda,113,74,7178,13,1244,26,2483,Low Confidence,28,Latin America and the Caribbean,https://www.unep.org/resources/report/unep-foo...
6,Argentina,116,72,3243563,16,700380,28,1238100,Very Low Confidence,32,Latin America and the Caribbean,https://www.unep.org/resources/report/unep-foo...
7,Armenia,137,93,275195,16,46259,28,81775,Very Low Confidence,51,Western Asia,https://www.unep.org/resources/report/unep-foo...
8,Aruba,113,74,7858,13,1362,26,2718,Low Confidence,533,Latin America and the Caribbean,https://www.unep.org/resources/report/unep-foo...
9,Australia,133,102,2563110,9,238248,22,546340,High Confidence,36,Australia and New Zealand,https://www.unep.org/resources/report/unep-foo...
10,Austria,76,39,349249,9,77289,28,254191,High Confidence,40,Western Europe,https://www.unep.org/resources/report/unep-foo...
11,Azerbaijan,137,93,934872,16,157148,28,277800,Very Low Confidence,31,Western Asia,https://www.unep.org/resources/report/unep-foo...
12,Bahamas,113,74,28792,13,4990,26,9960,Low Confidence,44,Latin America and the Caribbean,https://www.unep.org/resources/report/unep-foo...
13,Bahrain,171,132,216161,13,21026,26,41966,Low Confidence,48,Western Asia,https://www.unep.org/resources/report/unep-foo...
14,Bangladesh,84,65,10618233,16,2550080,3,544436,Very Low Confidence,50,Southern Asia,https://www.unep.org/resources/report/unep-foo...
15,Barbados,113,74,21215,13,3677,26,7339,Low Confidence,52,Latin America and the Caribbean,https://www.unep.org/resources/report/unep-foo...
16,Belarus,112,68,646356,16,147838,28,261341,Very Low Confidence,112,Eastern Europe,https://www.unep.org/resources/report/unep-foo...
17,Belgium,80,50,576036,10,112100,20,227371,Medium Confidence,56,Western Europe,https://www.unep.org/resources/report/unep-foo...
18,Belize,97,53,20564,16,6106,28,10794,Very Low Confidence,84,Latin America and the Caribbean,https://www.unep.org/resources/report/unep-foo...
19,Benin,144,100,1175297,16,184573,28,326280,Very Low Confidence,204,Sub-Saharan Africa,https://www.unep.org/resources/report/unep-foo...

In [161]:
data.tail(20)

,Country,combined figures (kg/capita/year),Household estimate (kg/capita/year),Household estimate (tonnes/year),Retail estimate (kg/capita/year),Retail estimate (tonnes/year),Food service estimate (kg/capita/year),Food service estimate (tonnes/year),Confidence in estimate,M49 code,Region,Source
194,Tunisia,135,91,1064407,16,182908,28,323336,Very Low Confidence,788,Northern Africa,https://www.unep.org/resources/report/unep-foo...
195,Turkey,137,93,7762575,16,1304858,28,2306668,Very Low Confidence,792,Western Asia,https://www.unep.org/resources/report/unep-foo...
196,Turkmenistan,120,76,449895,16,92936,28,164288,Very Low Confidence,795,Central Asia,https://www.unep.org/resources/report/unep-foo...
197,Turks and Caicos Islands,113,74,2824,13,489,26,977,Low Confidence,796,Latin America and the Caribbean,https://www.unep.org/resources/report/unep-foo...
198,Tuvalu,120,76,878,16,181,28,321,Very Low Confidence,798,Polynesia,https://www.unep.org/resources/report/unep-foo...
199,Uganda,147,103,4546237,16,692387,28,1223969,Very Low Confidence,800,Sub-Saharan Africa,https://www.unep.org/resources/report/unep-foo...
200,Ukraine,120,76,3344904,16,688070,28,1216338,Very Low Confidence,804,Eastern Europe,https://www.unep.org/resources/report/unep-foo...
201,United Arab Emirates,134,95,923625,13,125173,26,249836,Low Confidence,784,Western Asia,https://www.unep.org/resources/report/unep-foo...
202,United Kingdom,98,77,5199825,4,283627,17,1114248,High Confidence,826,Northern Europe,https://www.unep.org/resources/report/unep-foo...
203,United Rep. of Tanzania,163,119,6907649,16,907219,28,1603740,Very Low Confidence,834,Sub-Saharan Africa,https://www.unep.org/resources/report/unep-foo...
204,United States of America,139,59,19359951,16,5151313,64,20934827,High Confidence,840,Northern America,https://www.unep.org/resources/report/unep-foo...
205,United States Virgin Islands,113,74,7732,13,1340,26,2675,Low Confidence,850,Latin America and the Caribbean,https://www.unep.org/resources/report/unep-foo...
206,Uruguay,113,74,255892,13,44349,26,88517,Low Confidence,858,Latin America and the Caribbean,https://www.unep.org/resources/report/unep-foo...
207,Uzbekistan,135,91,3001868,16,515841,28,911881,Very Low Confidence,860,Central Asia,https://www.unep.org/resources/report/unep-foo...
208,Vanuatu,135,91,27296,16,4691,28,8292,Very Low Confidence,548,Melanesia,https://www.unep.org/resources/report/unep-foo...
209,Venezuela (Boliv. Rep. of),116,72,2065461,16,445994,28,788407,Very Low Confidence,862,Latin America and the Caribbean,https://www.unep.org/resources/report/unep-foo...
210,Viet Nam,120,76,7346717,16,1508689,28,2666991,Very Low Confidence,704,South-eastern Asia,https://www.unep.org/resources/report/unep-foo...
211,Yemen,148,104,3026946,16,456099,28,806270,Very Low Confidence,887,Western Asia,https://www.unep.org/resources/report/unep-foo...
212,Zambia,122,78,1391729,16,279350,28,493822,Very Low Confidence,894,Sub-Saharan Africa,https://www.unep.org/resources/report/unep-foo...
213,Zimbabwe,144,100,1458564,16,229059,28,404920,Very Low Confidence,716,Sub-Saharan Africa,https://www.unep.org/resources/report/unep-foo...

In [162]:
data[['Country','Region']].tail(20)

                          Country                           Region
194                       Tunisia                  Northern Africa
195                        Turkey                     Western Asia
196                  Turkmenistan                     Central Asia
197      Turks and Caicos Islands  Latin America and the Caribbean
198                        Tuvalu                        Polynesia
199                        Uganda               Sub-Saharan Africa
200                       Ukraine                   Eastern Europe
201          United Arab Emirates                     Western Asia
202                United Kingdom                  Northern Europe
203       United Rep. of Tanzania               Sub-Saharan Africa
204      United States of America                 Northern America
205  United States Virgin Islands  Latin America and the Caribbean
206                       Uruguay  Latin America and the Caribbean
207                    Uzbekistan                     Central Asia
208                       Vanuatu                        Melanesia
209    Venezuela (Boliv. Rep. of)  Latin America and the Caribbean
210                      Viet Nam               South-eastern Asia
211                         Yemen                     Western Asia
212                        Zambia               Sub-Saharan Africa
213                      Zimbabwe               Sub-Saharan Africa

In [163]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 12 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Country                                 214 non-null    object
 1   combined figures (kg/capita/year)       214 non-null    int64
 2   Household estimate (kg/capita/year)     214 non-null    int64
 3   Household estimate (tonnes/year)        214 non-null    int64
 4   Retail estimate (kg/capita/year)        214 non-null    int64
 5   Retail estimate (tonnes/year)           214 non-null    int64
 6   Food service estimate (kg/capita/year)  214 non-null    int64
 7   Food service estimate (tonnes/year)     214 non-null    int64
 8   Confidence in estimate                  214 non-null    object
 9   M49 code                                214 non-null    int64
 10  Region                                  214 non-null    object
 11  Source                                  214 non-null    object
dtypes: int64(8), object(4)
memory usage: 20.2+ KB

In [164]:
data['Region'].describe()

count                    214
unique                    17
top       Sub-Saharan Africa
freq                      48
Name: Region, dtype: object

In [165]:
confidence = LabelEncoder()
region = LabelEncoder()

In [166]:
data['Confidence in estimate'] = confidence.fit_transform(data['Confidence in estimate'])
data['Region'] = region.fit_transform(data['Region'])

In [167]:
data.head()

,Country,combined figures (kg/capita/year),Household estimate (kg/capita/year),Household estimate (tonnes/year),Retail estimate (kg/capita/year),Retail estimate (tonnes/year),Food service estimate (kg/capita/year),Food service estimate (tonnes/year),Confidence in estimate,M49 code,Region,Source
0,Afghanistan,126,82,3109153,16,594982,28,1051783,3,4,12,https://www.unep.org/resources/report/unep-foo...
1,Albania,127,83,238492,16,45058,28,79651,3,8,13,https://www.unep.org/resources/report/unep-foo...
2,Algeria,135,91,3918529,16,673360,28,1190335,3,12,7,https://www.unep.org/resources/report/unep-foo...
3,Andorra,123,84,6497,13,988,26,1971,1,20,13,https://www.unep.org/resources/report/unep-foo...
4,Angola,144,100,3169523,16,497755,28,879908,3,24,14,https://www.unep.org/resources/report/unep-foo...

In [168]:
features = ['Household estimate (kg/capita/year)', 'Retail estimate (kg/capita/year)', 
            'Food service estimate (kg/capita/year)', 'Confidence in estimate', 'Region']
target = 'combined figures (kg/capita/year)'

In [169]:
X = data[features]
y = data[target]

In [170]:
X

,Household estimate (kg/capita/year),Retail estimate (kg/capita/year),Food service estimate (kg/capita/year),Confidence in estimate,Region
0,82,16,28,3,12
1,83,16,28,3,13
2,91,16,28,3,7
3,84,13,26,1,13
4,100,16,28,3,14
...,...,...,...,...,...
209,72,16,28,3,4
210,76,16,28,3,11
211,104,16,28,3,15
212,78,16,28,3,14
213,100,16,28,3,14

In [171]:
y

0      126
1      127
2      135
3      123
4      144
      ...
209    116
210    120
211    148
212    122
213    144
Name: combined figures (kg/capita/year), Length: 214, dtype: int64

In [172]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=12)

In [173]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(149, 5)
(65, 5)
(149,)
(65,)

In [174]:
model = RandomForestRegressor(random_state=42)

In [175]:
model.fit(X_train, y_train)

# Predictions and Evaluation
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
rmse = mse ** 0.5

# Display the RMSE
print(f'Root Mean Squared Error (RMSE): {rmse}')

Root Mean Squared Error (RMSE): 7.870929766210304

In [176]:
y_pred

array([135.9 , 123.8 , 147.  , 144.  , 116.  , 139.77, 134.15, 113.  ,
       136.79, 109.35, 144.  , 116.  , 130.1 , 122.43, 147.  , 136.79,
       122.76, 185.04, 171.11, 101.12, 120.21, 145.29,  99.81, 122.15,
       134.15, 132.6 , 126.72, 133.52, 115.  , 126.72, 123.8 , 116.68,
       115.  , 111.44, 135.  , 118.01, 135.9 , 113.  , 113.  , 144.  ,
       147.  , 147.  , 147.  , 116.  , 100.64, 117.96, 135.  , 119.96,
       173.15, 126.72, 113.  , 144.  , 148.52, 120.09, 144.  , 103.15,
       110.32, 172.41, 122.78, 113.  , 111.46, 101.77, 135.9 , 113.  ,
       110.32])

In [180]:
X_test

,Household estimate (kg/capita/year),Retail estimate (kg/capita/year),Food service estimate (kg/capita/year),Confidence in estimate,Region
131,92,16,28,3,14
86,80,16,28,3,4
177,103,16,28,3,14
31,100,16,28,3,14
209,72,16,28,3,4
...,...,...,...,...,...
125,72,13,26,1,16
63,78,5,17,2,9
24,92,16,28,3,14
8,74,13,26,1,4
40,71,13,26,1,2

In [182]:
y_test

131    136
86     124
177    147
31     144
209    116
      ...
125    111
63     100
24     136
8      113
40     110
Name: combined figures (kg/capita/year), Length: 65, dtype: int64